[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
