[build]
  command = "npm run build"
  functions = ".netlify/functions"
  image = "ubuntu-20.04"  # Use Ubuntu 20.04 which has Nmap available in the package manager

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"  # Next.js requires Node.js 18 or higher

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Security headers are now managed in src/middleware.ts
